# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/keith/xilProjects/artyFTDI/artyFTDI.cache/wt [current_project]
set_property parent.project_path /home/keith/xilProjects/artyFTDI/artyFTDI.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /home/keith/xilProjects/artyFTDI/artyFTDI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/new/mod_m_counter.vhd
  /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/new/uart_tx.vhd
  /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/new/uartFTDI.vhd
}
read_ip -quiet /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/constrs_1/new/artyConstr.xdc
set_property used_in_implementation false [get_files /home/keith/xilProjects/artyFTDI/artyFTDI.srcs/constrs_1/new/artyConstr.xdc]


synth_design -top uartFTDI -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef uartFTDI.dcp

catch { report_utilization -file uartFTDI_utilization_synth.rpt -pb uartFTDI_utilization_synth.pb }
